# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-sno
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno-v6-vfs"
  namespace: "sno-v6-vfs"
spec:
  baseDomain: "example.ocp"
  pullSecretRef:
    name: "pull-secret"
  clusterImageSetNameRef: "img4.14.27-x86-64-appsub"
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKRtY9wygYTlmww8MBMXROnvAhPzQPBHgyRffi3YYAU6 tohayash@lab"
  clusters:
  - clusterName: "sno-v6-vfs"
    networkType: "OVNKubernetes"
    #installConfigOverrides:  "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"marketplace\", \"NodeTuning\" ] }}"
    clusterLabels:
      du-profile: "4.14"
      common: true
      group-du-sno: ""
      sites : "sno-v6-vfs"
    clusterNetwork:
      - cidr: 1001:1::/48
        hostPrefix: 64
    machineNetwork:
      - cidr: fc00:cc00:106:1123:1::0/80
    serviceNetwork:
      - 1001:2::/112
    additionalNTPSources:
      - fc00:cc00:106:1123::fff1
    cpuPartitioningMode: AllNodes
    nodes:
      - hostName: "sno.sno-v6-vfs.example.ocp"
        role: "master"
        bmcAddress: "redfish-virtualmedia+http://[fc00:cc00:106:1123::fff2]:8000/redfish/v1/Systems/06e17879-37b4-4093-9881-abc7aad178e0"
        bmcCredentialsName:
          name: "sno-bmc-secret"
        bootMACAddress: "52:54:00:3d:9e:03"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/vda"
        nodeNetwork:
          interfaces:
            - name: ens3
              macAddress: "52:54:00:3d:9e:03"
          config:
            interfaces:
              - name: ens3
                type: ethernet
                state: up
                ipv6:
                  enabled: true
                  address:
                  - ip: fc00:cc00:106:1123:1::fff
                    prefix-length: 64
                ipv4:
                  enabled: false
            dns-resolver:
              config:
                server:
                  - fc00:cc00:106:1123::fff1
            routes:
              config:
                - destination: ::/0
                  next-hop-address: fc00:cc00:106:1123::fff1
                  next-hop-interface: ens3
                  table-id: 254
